# permissions for end users to view networks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-viewer-role
rules:
  - apiGroups:
      - network.edgefarm.io
    resources:
      - networks
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - network.edgefarm.io
    resources:
      - networks/status
    verbs:
      - get
