# permissions for end users to edit participants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: participants-editor-role
rules:
  - apiGroups:
      - network.edgefarm.io
    resources:
      - participants
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - network.edgefarm.io
    resources:
      - participants/status
    verbs:
      - get
