# permissions for end users to view participants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: participants-viewer-role
rules:
  - apiGroups:
      - network.edgefarm.io
    resources:
      - participants
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - network.edgefarm.io
    resources:
      - participants/status
    verbs:
      - get
