@startuml
package "global-network" as global_network {
    database "global nats" as global_nats
}

package "anck " {
    [anck] as anck
    [anck-credentials] as anck_credentials
    anck <-l- anck_credentials
}


anck -l-> global_nats : configure streams
@enduml
