name: 'delete-pr-image'

on:
  pull_request:
    types: [closed]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.1
        with:
          owner: edgefarm
          name: ${{ env.IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: pr-${{github.event.pull_request.number}}