name: "release-image-head"

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - beta
      - main

jobs:
  release_image:
    uses: ./.github/workflows/release-image.yml